import type { Transaction, CreditCard, Promotion } from "@/types";

export const sampleCards: CreditCard[] = [
  {
    id: "card1",
    name: "Premium Rewards",
    lastFourDigits: "4521",
    brand: "visa",
    balance: 2450.75,
    limit: 10000,
    settlementDate: 25,
    color: "#1A1F71",
  },
  {
    id: "card2",
    name: "Travel Plus",
    lastFourDigits: "8832",
    brand: "mastercard",
    balance: 1280.50,
    limit: 15000,
    settlementDate: 15,
    color: "#EB001B",
  },
  {
    id: "card3",
    name: "Gold Card",
    lastFourDigits: "3001",
    brand: "amex",
    balance: 890.25,
    limit: 20000,
    settlementDate: 1,
    color: "#006FCF",
  },
];

export const sampleTransactions: Transaction[] = [
  {
    id: "t1",
    amount: 156.80,
    merchant: "Whole Foods Market",
    category: "supermarket",
    cardId: "card1",
    date: new Date(Date.now() - 1000 * 60 * 60 * 2).toISOString(),
    description: "Weekly groceries",
  },
  {
    id: "t2",
    amount: 89.50,
    merchant: "United Airlines",
    category: "travel",
    cardId: "card2",
    date: new Date(Date.now() - 1000 * 60 * 60 * 24).toISOString(),
    description: "Flight booking fee",
  },
  {
    id: "t3",
    amount: 45.00,
    merchant: "The Cheesecake Factory",
    category: "dining",
    cardId: "card1",
    date: new Date(Date.now() - 1000 * 60 * 60 * 48).toISOString(),
    description: "Dinner",
  },
  {
    id: "t4",
    amount: 299.99,
    merchant: "Apple Store",
    category: "shopping",
    cardId: "card3",
    date: new Date(Date.now() - 1000 * 60 * 60 * 72).toISOString(),
    description: "AirPods Pro",
  },
  {
    id: "t5",
    amount: 125.00,
    merchant: "Electric Company",
    category: "bills",
    cardId: "card1",
    date: new Date(Date.now() - 1000 * 60 * 60 * 96).toISOString(),
    description: "Monthly electricity",
  },
  {
    id: "t6",
    amount: 67.30,
    merchant: "Costco",
    category: "supermarket",
    cardId: "card2",
    date: new Date(Date.now() - 1000 * 60 * 60 * 120).toISOString(),
    description: "Bulk shopping",
  },
];

export const samplePromotions: Promotion[] = [
  {
    id: "p1",
    title: "5% Cashback at Supermarkets",
    description: "Earn 5% cashback on all supermarket purchases. Maximum cashback $50 per month.",
    category: "supermarket",
    cardId: "card1",
    discount: "5%",
    startDate: new Date().toISOString(),
    endDate: new Date(Date.now() + 1000 * 60 * 60 * 24 * 30).toISOString(),
    terms: "Valid at participating supermarkets. Excludes alcohol and tobacco products.",
    synced: false,
  },
  {
    id: "p2",
    title: "Double Miles on Travel",
    description: "Earn 2x miles on all travel bookings including flights, hotels, and car rentals.",
    category: "travel",
    cardId: "card2",
    discount: "2x Miles",
    startDate: new Date().toISOString(),
    endDate: new Date(Date.now() + 1000 * 60 * 60 * 24 * 60).toISOString(),
    terms: "Applies to travel purchases over $50. Book through card portal for bonus.",
    synced: false,
  },
  {
    id: "p3",
    title: "10% Off Dining",
    description: "Get 10% off at select restaurants when you pay with your card.",
    category: "dining",
    cardId: "card1",
    discount: "10%",
    startDate: new Date().toISOString(),
    endDate: new Date(Date.now() + 1000 * 60 * 60 * 24 * 14).toISOString(),
    terms: "Maximum discount $25 per transaction. Valid at participating restaurants.",
    synced: false,
  },
  {
    id: "p4",
    title: "Free Shipping at Top Retailers",
    description: "Enjoy free standard shipping at major online retailers with your Gold Card.",
    category: "shopping",
    cardId: "card3",
    discount: "Free Shipping",
    startDate: new Date().toISOString(),
    endDate: new Date(Date.now() + 1000 * 60 * 60 * 24 * 45).toISOString(),
    terms: "Valid at Amazon, Target, Walmart, and other select retailers.",
    synced: false,
  },
];
